-- Coursemap deliberately has no default catalogue or user fixtures.
--
-- Run `npm run db:reset` for the guarded local preview seed. Keeping this
-- default file empty prevents hosted preview and remote seed workflows from
-- creating the predictable local-only demonstration administrator.
