begin;
select plan(20);
insert into auth.users(id,email) values ('e1212902-a316-4905-a12d-f2560ee3c911','models@example.test');
update private.user_roles set role_id=(select id from private.app_roles where key='admin') where user_id='e1212902-a316-4905-a12d-f2560ee3c911';
insert into private.role_permissions(role_id,permission_id)
select r.id,p.id from private.app_roles r cross join private.app_permissions p where r.key='admin' and p.key='imports.manage' on conflict do nothing;
select set_config('request.jwt.claim.sub','e1212902-a316-4905-a12d-f2560ee3c911',true);
set local role authenticated;
select lives_ok($$insert into public.import_models(id,name,provider,input_usd_per_million,output_usd_per_million) values ('test/new-model','New model','Test',0.1,0.2)$$,'import admins can add priced models');
select is((select count(*) from public.import_models where id='test/new-model'),1::bigint,'import admins can read models');
select lives_ok($$update public.app_settings set value='"test/new-model"' where key='imports.model'$$,'an enabled model can become the default');
select throws_ok($$update public.import_models set enabled=false where id='test/new-model'$$,'22023','Choose another default model before removing this model.','the selected default cannot be disabled');
select throws_ok($$update public.import_models set visible=false where id='test/new-model'$$,'22023','Choose another default model before hiding this model.','the default cannot be hidden');
select throws_ok($$update public.import_models set input_usd_per_million=-1 where id='test/new-model'$$,'23514',null,'negative pricing is rejected');
update public.app_settings set value='"google/gemini-3.1-flash-lite"' where key='imports.model';
select lives_ok($$update public.import_models set visible=false where id='test/new-model'$$,'unused models can be hidden');
select is((select count(*) from public.import_models where id='test/new-model' and enabled and not visible),1::bigint,'hidden models remain in management');
select throws_ok($$update public.app_settings set value='"test/new-model"' where key='imports.model'$$,'22023','Choose an enabled import model.','hidden models cannot become the default');
reset role;
select throws_ok($$insert into public.course_import_runs(requested_model) values ('test/new-model')$$,'22023','Choose an enabled import model.','hidden models cannot enter the course queue');
select throws_ok($$insert into public.academic_structure_import_runs(requested_model) values ('test/new-model')$$,'22023','Choose an enabled import model.','hidden models cannot enter the structure queue');
set local role authenticated;
select lives_ok($$update public.import_models set enabled=false where id='test/new-model'$$,'unused models can be disabled');
select throws_ok($$update public.app_settings set value='"test/new-model"' where key='imports.model'$$,'22023','Choose an enabled import model.','disabled models cannot become the default');
select throws_ok($$delete from public.import_models where id='test/new-model'$$,'42501',null,'catalogue history cannot be deleted');
reset role;
update private.user_roles set role_id=(select id from private.app_roles where key='user') where user_id='e1212902-a316-4905-a12d-f2560ee3c911';
set local role authenticated;
select is((select count(*) from public.import_models),0::bigint,'ordinary users cannot read the model catalogue');
select throws_ok($$insert into public.import_models(id,name,provider) values ('test/forbidden','Forbidden','Test')$$,'42501',null,'ordinary users cannot add models');
with changed as (update public.import_models set enabled=true where id='test/new-model' returning id) select is((select count(*) from changed),0::bigint,'ordinary users cannot change models');
set local role anon;
select throws_ok($$select * from public.import_models$$,'42501',null,'anonymous access is denied');
reset role;
select throws_ok($$insert into public.course_import_runs(requested_model) values ('test/new-model')$$,'22023','Choose an enabled import model.','disabled models cannot enter the course queue');
select throws_ok($$insert into public.academic_structure_import_runs(requested_model) values ('test/new-model')$$,'22023','Choose an enabled import model.','disabled models cannot enter the structure queue');
select * from finish();
rollback;
