// Generated by scripts/sync-reui-free-components.mjs.
// Source: keenthemes/reui registry-reui Radix catalogue.

export type ReuiCatalogueNavigationCategory = {
  readonly name: string;
  readonly label: string;
  readonly count: number;
};

export const reuiCatalogueNavigationCategories = [
  {
    "name": "accordion",
    "label": "Accordion",
    "count": 11
  },
  {
    "name": "alert",
    "label": "Alert",
    "count": 20
  },
  {
    "name": "alert-dialog",
    "label": "Alert Dialog",
    "count": 14
  },
  {
    "name": "aspect-ratio",
    "label": "Aspect Ratio",
    "count": 8
  },
  {
    "name": "autocomplete",
    "label": "Autocomplete",
    "count": 12
  },
  {
    "name": "avatar",
    "label": "Avatar",
    "count": 35
  },
  {
    "name": "badge",
    "label": "Badge",
    "count": 25
  },
  {
    "name": "breadcrumb",
    "label": "Breadcrumb",
    "count": 15
  },
  {
    "name": "button",
    "label": "Button",
    "count": 61
  },
  {
    "name": "button-group",
    "label": "Button Group",
    "count": 57
  },
  {
    "name": "calendar",
    "label": "Calendar",
    "count": 30
  },
  {
    "name": "card",
    "label": "Card",
    "count": 18
  },
  {
    "name": "carousel",
    "label": "Carousel",
    "count": 11
  },
  {
    "name": "cascader",
    "label": "Cascader",
    "count": 20
  },
  {
    "name": "chart",
    "label": "Chart",
    "count": 25
  },
  {
    "name": "checkbox",
    "label": "Checkbox",
    "count": 22
  },
  {
    "name": "code-block",
    "label": "Code Block",
    "count": 27
  },
  {
    "name": "collapsible",
    "label": "Collapsible",
    "count": 10
  },
  {
    "name": "combobox",
    "label": "Combobox",
    "count": 28
  },
  {
    "name": "command",
    "label": "Command",
    "count": 8
  },
  {
    "name": "context-menu",
    "label": "Context Menu",
    "count": 10
  },
  {
    "name": "data-grid",
    "label": "Data Grid",
    "count": 34
  },
  {
    "name": "date-selector",
    "label": "Date Selector",
    "count": 4
  },
  {
    "name": "dialog",
    "label": "Dialog",
    "count": 10
  },
  {
    "name": "drawer",
    "label": "Drawer",
    "count": 5
  },
  {
    "name": "dropdown-menu",
    "label": "Dropdown Menu",
    "count": 18
  },
  {
    "name": "empty",
    "label": "Empty",
    "count": 20
  },
  {
    "name": "event-calendar",
    "label": "Event Calendar",
    "count": 5
  },
  {
    "name": "field",
    "label": "Field",
    "count": 11
  },
  {
    "name": "file-upload",
    "label": "File Upload",
    "count": 10
  },
  {
    "name": "filters",
    "label": "Filters",
    "count": 12
  },
  {
    "name": "frame",
    "label": "Frame",
    "count": 19
  },
  {
    "name": "gantt",
    "label": "Gantt",
    "count": 7
  },
  {
    "name": "hover-card",
    "label": "Hover Card",
    "count": 8
  },
  {
    "name": "icon-stack",
    "label": "Icon Stack",
    "count": 6
  },
  {
    "name": "icon-tile",
    "label": "Icon Tile",
    "count": 17
  },
  {
    "name": "input",
    "label": "Input",
    "count": 31
  },
  {
    "name": "input-group",
    "label": "Input Group",
    "count": 40
  },
  {
    "name": "input-otp",
    "label": "Input Otp",
    "count": 6
  },
  {
    "name": "item",
    "label": "Item",
    "count": 12
  },
  {
    "name": "kanban",
    "label": "Kanban",
    "count": 6
  },
  {
    "name": "kbd",
    "label": "Kbd",
    "count": 6
  },
  {
    "name": "label",
    "label": "Label",
    "count": 13
  },
  {
    "name": "menubar",
    "label": "Menubar",
    "count": 5
  },
  {
    "name": "native-select",
    "label": "Native Select",
    "count": 6
  },
  {
    "name": "navigation-menu",
    "label": "Navigation Menu",
    "count": 4
  },
  {
    "name": "number-field",
    "label": "Number Field",
    "count": 6
  },
  {
    "name": "pagination",
    "label": "Pagination",
    "count": 15
  },
  {
    "name": "phone-input",
    "label": "Phone Input",
    "count": 8
  },
  {
    "name": "popover",
    "label": "Popover",
    "count": 11
  },
  {
    "name": "progress",
    "label": "Progress",
    "count": 8
  },
  {
    "name": "radio-group",
    "label": "Radio Group",
    "count": 17
  },
  {
    "name": "rating",
    "label": "Rating",
    "count": 9
  },
  {
    "name": "resizable",
    "label": "Resizable",
    "count": 10
  },
  {
    "name": "scroll-area",
    "label": "Scroll Area",
    "count": 5
  },
  {
    "name": "scrollspy",
    "label": "Scrollspy",
    "count": 2
  },
  {
    "name": "select",
    "label": "Select",
    "count": 33
  },
  {
    "name": "separator",
    "label": "Separator",
    "count": 6
  },
  {
    "name": "sheet",
    "label": "Sheet",
    "count": 4
  },
  {
    "name": "skeleton",
    "label": "Skeleton",
    "count": 10
  },
  {
    "name": "slider",
    "label": "Slider",
    "count": 12
  },
  {
    "name": "sonner",
    "label": "Sonner",
    "count": 21
  },
  {
    "name": "sortable",
    "label": "Sortable",
    "count": 8
  },
  {
    "name": "spinner",
    "label": "Spinner",
    "count": 12
  },
  {
    "name": "stepper",
    "label": "Stepper",
    "count": 15
  },
  {
    "name": "switch",
    "label": "Switch",
    "count": 14
  },
  {
    "name": "table",
    "label": "Table",
    "count": 17
  },
  {
    "name": "tabs",
    "label": "Tabs",
    "count": 9
  },
  {
    "name": "textarea",
    "label": "Textarea",
    "count": 6
  },
  {
    "name": "timeline",
    "label": "Timeline",
    "count": 12
  },
  {
    "name": "toggle",
    "label": "Toggle",
    "count": 14
  },
  {
    "name": "toggle-group",
    "label": "Toggle Group",
    "count": 16
  },
  {
    "name": "tooltip",
    "label": "Tooltip",
    "count": 16
  },
  {
    "name": "tree",
    "label": "Tree",
    "count": 7
  }
] satisfies readonly ReuiCatalogueNavigationCategory[];
