export const reuiCatalogueGroups = [
  {
    slug: "actions",
    label: "Actions",
    categories: [
      "button",
      "button-group",
      "command",
      "context-menu",
      "dropdown-menu",
      "menubar",
      "navigation-menu",
      "toggle",
      "toggle-group",
    ],
  },
  {
    slug: "forms",
    label: "Inputs & forms",
    categories: [
      "autocomplete",
      "calendar",
      "cascader",
      "checkbox",
      "combobox",
      "date-selector",
      "field",
      "file-upload",
      "input",
      "input-group",
      "input-otp",
      "label",
      "native-select",
      "number-field",
      "phone-input",
      "radio-group",
      "rating",
      "select",
      "slider",
      "switch",
      "textarea",
    ],
  },
  {
    slug: "feedback",
    label: "Feedback & overlays",
    categories: [
      "alert",
      "alert-dialog",
      "dialog",
      "drawer",
      "empty",
      "hover-card",
      "popover",
      "progress",
      "sheet",
      "skeleton",
      "sonner",
      "spinner",
      "tooltip",
    ],
  },
  {
    slug: "content",
    label: "Content & layout",
    categories: [
      "accordion",
      "aspect-ratio",
      "avatar",
      "badge",
      "breadcrumb",
      "card",
      "carousel",
      "collapsible",
      "frame",
      "icon-stack",
      "icon-tile",
      "item",
      "kbd",
      "pagination",
      "resizable",
      "scroll-area",
      "scrollspy",
      "separator",
      "table",
      "tabs",
      "timeline",
    ],
  },
  {
    slug: "workflows",
    label: "Data & workflows",
    categories: [
      "chart",
      "code-block",
      "data-grid",
      "event-calendar",
      "filters",
      "gantt",
      "kanban",
      "sortable",
      "stepper",
      "tree",
    ],
  },
] as const;

export type ReuiCatalogueGroupSlug =
  (typeof reuiCatalogueGroups)[number]["slug"];

export function findReuiCatalogueGroup(slug: string) {
  return reuiCatalogueGroups.find((group) => group.slug === slug);
}
